### ISSUE TITLE
Doesn't run on OSX

### ISSUE THREAD

**Issue by milo-trujillo** [bonsaiviking/NfSpy#2]
Hi there, trying to use your tool on OSX 10.9.2, and the project builds and installs cleanly, but when running I get the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/nfspysh", line 3, in <module>
    from nfspy import NfSpy, NFSError, NF3DIR
  File "/Library/Python/2.7/site-packages/nfspy/__init__.py", line 3, in <module>
    from nfspy import *
  File "/Library/Python/2.7/site-packages/nfspy/nfspy.py", line 10, in <module>
    from nfsclient import *
  File "/Library/Python/2.7/site-packages/nfspy/nfsclient.py", line 14, in <module>
    class NFSError(Exception):
  File "/Library/Python/2.7/site-packages/nfspy/nfsclient.py", line 66, in NFSError
    NFS3ERR_BADHANDLE    :  errno.EBADR,
AttributeError: 'module' object has no attribute 'EBADR'
```

Any help would be appreciated. I'm using Python 2.7.5.

**Comment by milo-trujillo** [comment]
Awesome, thank you!
