### ISSUE TITLE
self.handles.d - AttributeError: 'NoneType' object has no attribute 'd'

### ISSUE THREAD

**Issue by maaaaz** [bonsaiviking/NfSpy#6]
Hello there,

I would like to report a bug faced while mounting an share with 'everybody' as ACL
```
$ nfspy -d -o server=<server>:/<path>,allow_other,ro,intr /mnt/test
FUSE library version: 2.9.7
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.26
flags=0x001ffffb
max_readahead=0x00020000

   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
unique: 2, opcode: ACCESS (34), nodeid: 1, insize: 48, pid: 4590
access / 04
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/fuse.py", line 362, in __call__
    return apply(self.func, args, kw)
  File "/usr/lib/python2.7/dist-packages/nfspy/nfspy.py", line 676, in access
    handle, fattr = self.gethandle(path)
  File "/usr/lib/python2.7/dist-packages/nfspy/nfspy.py", line 293, in gethandle
    if len(self.handles.d) >= self.handles.count:
AttributeError: 'NoneType' object has no attribute 'd'
   unique: 2, error: -22 (Invalid argument), outsize: 16
unique: 3, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 6867
getattr /
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/fuse.py", line 362, in __call__
    return apply(self.func, args, kw)
  File "/usr/lib/python2.7/dist-packages/nfspy/fusefs.py", line 23, in getattr
    st = NfSpy.getattr(self, path)
  File "/usr/lib/python2.7/dist-packages/nfspy/nfspy.py", line 303, in getattr
    handle, fattr = self.gethandle(path)
  File "/usr/lib/python2.7/dist-packages/nfspy/nfspy.py", line 293, in gethandle
    if len(self.handles.d) >= self.handles.count:
AttributeError: 'NoneType' object has no attribute 'd'
   unique: 3, error: -22 (Invalid argument), outsize: 16
unique: 4, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 6875
getattr /
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/fuse.py", line 362, in __call__
    return apply(self.func, args, kw)
  File "/usr/lib/python2.7/dist-packages/nfspy/fusefs.py", line 23, in getattr
    st = NfSpy.getattr(self, path)
  File "/usr/lib/python2.7/dist-packages/nfspy/nfspy.py", line 303, in getattr
    handle, fattr = self.gethandle(path)
  File "/usr/lib/python2.7/dist-packages/nfspy/nfspy.py", line 293, in gethandle
    if len(self.handles.d) >= self.handles.count:
AttributeError: 'NoneType' object has no attribute 'd'
   unique: 4, error: -22 (Invalid argument), outsize: 16
```
I should say that I know that the server supports NFSv4 but I don't know which was protocol was used for this bug.

Cheers.

**Comment by bonsaiviking** [comment]
It looks like something went wrong in filesystem initialization, but Fuse isn't letting us know exactly what. The best way to debug this is to use `nfspysh` instead; this will raise any NFS errors so we can see what exactly is going wrong. Once that's figured out, we can re-try with `nfspy` to create the Fuse filesystem mountpoint.
