### ISSUE TITLE
Cannot download/cd files or folders with spaces in the name

### ISSUE THREAD

**Issue by TopazA** [bonsaiviking/NfSpy#7]
Hi there.

I have tried to change directory or list directory contents of files with spaces in the name, but every attempt results in the errors shown below. 

```
nfspy@1.2.3.4:/dir:/subdir>cd test folder
ERROR:root:cd() takes exactly 2 arguments (3 given) 
Traceback (most recent call last):
  File "/usr/bin/nfspysh", line 42, in __call__
    func(*args[1:])
TypeError: cd() takes exactly 2 arguments (3 given)
Usage: cd <dir> 

```

```
nfspy@1.2.3.4:/dir:/subdir>cd test\ folder
ERROR:root:cd() takes exactly 2 arguments (3 given) 
Traceback (most recent call last):
  File "/usr/bin/nfspysh", line 42, in __call__
    func(*args[1:])
TypeError: cd() takes exactly 2 arguments (3 given)
Usage: cd <dir> 

```

```
nfspy@1.2.3.4:/dir:/subdir>cd 'test folder'
[Errno 2] No such file or directory: "/'test folder'"
nfspy@1.2.3.4:/dir:/subdir:/'test folder'> 

```

```
nfspy@1.2.3.4:/dir:/subdir>cd "test folder"
[Errno 2] No such file or directory: '/"test folder"'
nfspy@1.2.3.4:/dir:/subdir:/"test folder"> 

```

```
nfspy@1.2.3.4:/dir:/subdir>cd "test\ folder"
[Errno 5] Input/output error: '/"test\\ folder"'
nfspy@1.2.3.4:/dir:/subdir:/"test\ folder"> 
```

As a result, I'm unable to access the contents of these directories nor download any files from them.
Would appreciate it if this got fixed.
Thanks!

**Comment by sleirsgoevy** [comment]
Changing `posix=False` to `posix=True` in nfspysh fixes that.
